### ISSUE TITLE
Create Game Dialog does not register selected friend.

### ISSUE THREAD

**Issue by isaac-siegel** [MonkeyViewController/SnapThat#16]
I am not yet sure how to 100% reproduce this bug. 

It appears sometimes when you select a friend, then click FAB. Even though a friend is selected, the dialog says 0 friends selected. I think it may have something to do with the clicking the whole row as opposed to the checkbox, but I am unsure.

Proof:
![2015-05-18 05 59 44](https://cloud.githubusercontent.com/assets/3596386/7675102/d6f352ee-fce8-11e4-86b5-7ef11a819537.png)

**Comment by fewjative** [comment]
Fixed in navdrawer branch
